### ISSUE TITLE
Is there a typo?

### ISSUE THREAD

**Issue by TBrannon** [jacktripperz/bnbminer#1]
Not sure if I'm correct, but it seem there is a typo on line 178 of miner.py.
The line is  print("Expection occurred 5 times. Terminating!")
It seems like it should be:  print("Exception occurred 5 times. Terminating!")

I know, it's trivial, but I thought you might like to know.

**Comment by CasperNybroe** [comment]
Hi Brannon
It sure is a typo - thanks for letting me know. I will fix it straight away.

**Comment by jacktripperz** [comment]
Hi Brannon
It sure is a typo - thanks for letting me know. I will fix it straight away.
Changes are pushed.
